/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2a2a2a",
        "primary-container": "#00f2ff",
        "tertiary-container": "#67f4b7",
        "inverse-primary": "#00696f",
        "error": "#ffb4ab",
        "surface-container-low": "#1c1b1b",
        "on-surface-variant": "#b9cacb",
        "electric-cyan": "#00f2ff",
        "surface-container-highest": "#353534",
        "nebula-glass": "rgba(255, 255, 255, 0.03)",
        "secondary-fixed-dim": "#d1bcff",
        "secondary": "#d1bcff",
        "background": "#131313",
        "error-container": "#93000a",
        "secondary-fixed": "#e9ddff",
        "on-primary-fixed": "#002022",
        "inverse-on-surface": "#313030",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#004f54",
        "on-secondary-fixed": "#23005b",
        "on-primary-container": "#006a71",
        "surface-bright": "#3a3939",
        "surface-container": "#201f1f",
        "surface-dim": "#131313",
        "on-error-container": "#ffdad6",
        "surface-variant": "#353534",
        "purple-haze": "#7000ff",
        "surface-tint": "#00dbe7",
        "surface-container-lowest": "#0e0e0e",
        "primary": "#e1fdff",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-secondary-fixed-variant": "#5700c9",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary-container": "#ddcdff",
        "outline-variant": "#3a494b",
        "on-tertiary": "#003824",
        "outline": "#849495",
        "tertiary": "#e1ffec",
        "primary-fixed": "#74f5ff",
        "secondary-container": "#7000ff",
        "on-background": "#e5e2e1",
        "starlight-white": "#FFFFFF",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary": "#00363a",
        "on-surface": "#e5e2e1",
        "surface": "#131313",
        "on-secondary": "#3c0090",
        "primary-fixed-dim": "#00dbe7",
        "midnight-blue": "#0a0a1a",
        "on-tertiary-container": "#006e4b",
        "deep-space": "#050505",
        "emerald-pulse": "#10B981"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "80px",
        "margin-mobile": "20px",
        "base": "8px",
        "max-width": "1440px"
      },
      fontFamily: {
        "headline-lg": ["Sora", "sans-serif"],
        "display-lg-mobile": ["Sora", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "code-sm": ["14px", { lineHeight: "1.5", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
